name: schedule_data001

on:
  schedule:
    - cron: '57 11 * * *'


jobs:
  start:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - run: pip install dingtalkchatbot requests
      - run: python Staring_robot.py
