name: schedule_data

on:
  schedule:
    - cron: '15 11 * * *'


jobs:
  start:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - run: pip install dingtalkchatbot requests time datetime
      - run: python Staring robot.py


