name: schedule_test

on:
  schedule:
    - cron: '03 12 * * *'


jobs:
  start:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - run: pip install dingtalkchatbot requests
      - run: python Staring_robot.py
