name: Python application

on:
  schedule:
    - cron: '57 11 * * *'


jobs:
  start:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        with:
          python-version: 3.8
      - run: pip install dingtalkchatbot requests
      - run: python Staring_robot.py
